### ISSUE TITLE
Question: Support for .Net Core 3.1 ?

### ISSUE THREAD

**Issue by sekulicb** [GuOrg/Gu.Wpf.FlipView#13]
Hi. Is there any timeline when it comes to support for newer .NET Core framework?

Thanks

**Comment by sekulicb** [comment]
Follow-up: Is there a way to have vertical gestures, I need to mimic swiping. Thanks

**Comment by JohanLarsson** [comment]
> Is there any timeline when it comes to support for newer .NET Core framework
No timeline but should be easy and we m,ust fix it of course, thanks for the reminder.

>  Is there a way to have vertical gestures,
Not out-of-the-box as of now, only reason I never needed it.
Should be easy to add support I think. Do you mind creating a separate issue for this request?

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/Gu.Wpf.FlipView/2.0.2

**Comment by JohanLarsson** [comment]
Added support, forgot to close issue.
